spring.application.name=kinopoisk

# DATABASE (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/kinopoisk_bd
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate/JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# LIQUIBASE
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

# KINOPOISK
kinopoisk.api.url=https://kinopoiskapiunofficial.tech
kinopoisk.api.key=8cc18fb6-35f0-4568-be03-ce46673bacb4
kinopoisk.api.v2.films=/api/v2.2/films